"""Adicionando Pedido

Revision ID: 5069e465b8e7
Revises: e9df4c1976d3
Create Date: 2023-08-16 14:44:48.191228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5069e465b8e7'
down_revision: Union[str, None] = 'e9df4c1976d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
